import { useEffect, useRef, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, InputAdornment, MenuItem, Stack, TextField, Typography, useMediaQuery } from "@mui/material";
import { DownloadRounded, SearchRounded } from "@mui/icons-material";
import { DataGrid, GridColDef } from "@mui/x-data-grid";
import { api, Category, Expense, Ingestion, money } from "../api";
import ExpenseEditor from "../components/ExpenseEditor";

const colors:Record<string,"default"|"success"|"warning"|"error"|"info">={accepted:"success",needs_review:"warning",duplicate:"error",queued:"info",processing:"info",failed:"error"};
export default function ExpensesPage({reviewOnly=false,onChanged,initialExpenseId}:{reviewOnly?:boolean;onChanged?:()=>void;initialExpenseId?:string}) {
  const initialOpened = useRef(false);
  const [items,setItems]=useState<Expense[]>([]); const [ingestions,setIngestions]=useState<Ingestion[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [selected,setSelected]=useState<Expense|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [scope,setScope]=useState(""); const [category,setCategory]=useState(""); const mobile=useMediaQuery("(max-width:760px)");
  const load=()=>{setLoading(true); const p=new URLSearchParams(); if(reviewOnly)p.set("state","review"); if(search)p.set("search",search); if(scope)p.set("scope",scope); if(category)p.set("category_id",category); Promise.all([api<Expense[]>(`/api/expenses?${p}`),api<Category[]>("/api/categories"),reviewOnly?api<Ingestion[]>("/api/ingestions?limit=100"):Promise.resolve([])]).then(([e,c,i])=>{setItems(e);setCategories(c);setIngestions(i);if(initialExpenseId&&!initialOpened.current){initialOpened.current=true;const match=e.find(item=>item.id===initialExpenseId);if(match)setSelected(match);else api<Expense>(`/api/expenses/${initialExpenseId}`).then(setSelected).catch(()=>setError("The linked expense was not found."))}setError("")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[reviewOnly,search,scope,category]);
  const changed=()=>{load();onChanged?.()};
  const cols:GridColDef[]=[{field:"expense_date",headerName:"Date",width:115},{field:"merchant",headerName:"Merchant",flex:1,minWidth:170},{field:"category_name",headerName:"Category",width:150},{field:"scope",headerName:"Scope",width:110},{field:"payment_method_name",headerName:"Payment",width:140},{field:"amount",headerName:"Amount",width:125,align:"right",headerAlign:"right",valueFormatter:(v)=>money(v)},{field:"status",headerName:"Status",width:145,renderCell:p=><Chip size="small" color={colors[p.value]||"default"} label={String(p.value).replace("_"," ")}/> }];
  return <Stack spacing={3}><Box sx={{display:"flex",justifyContent:"space-between",gap:2,alignItems:"end",flexWrap:"wrap"}}><Box><Typography className="eyebrow">{reviewOnly?"Needs attention":"Complete ledger"}</Typography><Typography variant="h4" className="page-title">{reviewOnly?"Review inbox":"Expenses"}</Typography></Box>{!reviewOnly&&<Button href="/api/exports/expenses.csv?extended=true" startIcon={<DownloadRounded/>} variant="outlined">Export CSV</Button>}</Box>
    <Card><CardContent sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1fr 1fr"},gap:1.5}}><TextField size="small" placeholder="Search merchant or memo" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchRounded/></InputAdornment>}}/><TextField select size="small" label="Scope" value={scope} onChange={e=>setScope(e.target.value)}><MenuItem value="">All scopes</MenuItem>{["personal","business","unknown"].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select size="small" label="Category" value={category} onChange={e=>setCategory(e.target.value)}><MenuItem value="">All categories</MenuItem>{categories.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField></CardContent></Card>
    {error&&<Alert severity="error">{error}</Alert>}{reviewOnly&&ingestions.filter(i=>["queued","processing","failed"].includes(i.status)).map(i=><Alert key={i.id} severity={i.status==="failed"?"error":"info"}><strong>{i.status==="failed"?"Import failed":"Receipt processing"}</strong> · {i.source} · {new Date(i.received_at).toLocaleString()} · {i.id.slice(0,8)}{i.error_message?` — ${i.error_message}`:""}</Alert>)}{loading?<Box sx={{display:"grid",placeItems:"center",height:280}}><CircularProgress/></Box>:items.length===0?<Card><Box className="empty-state"><Typography variant="h6">{reviewOnly?"No receipts need review":"No expenses found"}</Typography><Typography>{reviewOnly&&ingestions.some(i=>["queued","processing"].includes(i.status))?"Your newest receipt is still processing.":"New receipts will appear here after processing."}</Typography></Box></Card>:mobile?<Stack spacing={1.5}>{items.map(e=><Card key={e.id} onClick={()=>setSelected(e)}><CardContent sx={{display:"flex",justifyContent:"space-between",gap:2}}><Box><Typography fontWeight={750}>{e.merchant||"Unknown merchant"}</Typography><Typography variant="body2" color="text.secondary">{e.expense_date||"No date"} · {e.category_name||"Uncategorised"}</Typography><Chip size="small" sx={{mt:1}} color={colors[e.status]||"default"} label={e.status.replace("_"," ")}/></Box><Typography fontWeight={750}>{money(e.amount)}</Typography></CardContent></Card>)}</Stack>:<Card><Box sx={{height:"min(68vh,720px)"}}><DataGrid rows={items} columns={cols} disableRowSelectionOnClick onRowClick={p=>setSelected(p.row as Expense)} initialState={{pagination:{paginationModel:{pageSize:25,page:0}}}} pageSizeOptions={[25,50,100]} sx={{border:0,"& .MuiDataGrid-row":{cursor:"pointer"}}}/></Box></Card>}
    <ExpenseEditor expense={selected} open={Boolean(selected)} onClose={()=>setSelected(null)} onChanged={changed}/>
  </Stack>;
}
